### ISSUE TITLE
XSS vulnerable

### ISSUE THREAD

**Issue by adamchainz** [hotwire-django/django-turbo-response#5]
The code in `renderers.py` uses f-strings to template HTML with HTML-escaping incoming strings. This means user content being used in a response could be reflected and rendered in the browser.

**Comment by danjac** [comment]
Good point, let's fix that.

**Comment by adamchainz** [comment]
You can do this by rendering via Django templates, jinja2, or `html.escape()`.

**Comment by danjac** [comment]
@adamchainz see https://github.com/hotwire-django/django-turbo-response/pull/6

**Comment by danjac** [comment]
The TurboStream and TurboFrame classes already have template classes/methods for handling template-based content, so you would likely do something like:

`TurboStream("target").append.template("tmpl.html", {}).render()`

So rendering in such cases is fine, as the HTML string is already handled with a Django templates.

What is probably better is having an "is_safe" argument to the renderer, set to False by default, which can be set to True with trusted content, e.g. if the content is already the result of Django template rendering.

**Comment by danjac** [comment]
Fixed in 0.0.39.
