### ISSUE TITLE
Question about the future

### ISSUE THREAD

**Issue by rtpm** [hotwire-django/django-turbo-response#7]
Hello,

I see that you have switched from Hotwire to htmx in one of your personal projects.
Does it mean you won't update djanto-turbo-response anymore ot just decided to use the other tool ?

I know there's been a lot of noise in Basecamp etc. and I am worried about the the future of Hotwire.

What is your opinion on that ?

Thanks for your work on the project and all the Howtire Django stuff.

**Comment by danjac** [comment]
I certainly plan on supporting django-turbo-response for the foreseeable future while there is a need for the library.  However it's probably feature complete given the small scope of the project and Turbo itself, so I will likely focus on bug fixes and minor tweaks in future releases.

Beyond that it really depends on whether Hotwire/Turbo is something Basecamp will support long term, or whether it is adopted as a community project.  In terms of larger mindshare and support outside the Rails community as well as features and support, it does seem at this point htmx is in a better place right now.
